// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: plugin.proto

package simsdkrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldType int32

const (
	FieldType_FIELD_TYPE_UNSPECIFIED FieldType = 0
	FieldType_STRING                 FieldType = 1
	FieldType_INT                    FieldType = 2
	FieldType_UINT                   FieldType = 3
	FieldType_FLOAT                  FieldType = 4
	FieldType_BOOL                   FieldType = 5
	FieldType_ENUM                   FieldType = 6
	FieldType_TIMESTAMP              FieldType = 7
	FieldType_REPEATED               FieldType = 8
	FieldType_OBJECT                 FieldType = 9
)

// Enum value maps for FieldType.
var (
	FieldType_name = map[int32]string{
		0: "FIELD_TYPE_UNSPECIFIED",
		1: "STRING",
		2: "INT",
		3: "UINT",
		4: "FLOAT",
		5: "BOOL",
		6: "ENUM",
		7: "TIMESTAMP",
		8: "REPEATED",
		9: "OBJECT",
	}
	FieldType_value = map[string]int32{
		"FIELD_TYPE_UNSPECIFIED": 0,
		"STRING":                 1,
		"INT":                    2,
		"UINT":                   3,
		"FLOAT":                  4,
		"BOOL":                   5,
		"ENUM":                   6,
		"TIMESTAMP":              7,
		"REPEATED":               8,
		"OBJECT":                 9,
	}
)

func (x FieldType) Enum() *FieldType {
	p := new(FieldType)
	*p = x
	return p
}

func (x FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[0].Descriptor()
}

func (FieldType) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[0]
}

func (x FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldType.Descriptor instead.
func (FieldType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type ManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestRequest) Reset() {
	*x = ManifestRequest{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestRequest) ProtoMessage() {}

func (x *ManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestRequest.ProtoReflect.Descriptor instead.
func (*ManifestRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type ManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *Manifest              `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestResponse) Reset() {
	*x = ManifestResponse{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestResponse) ProtoMessage() {}

func (x *ManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestResponse.ProtoReflect.Descriptor instead.
func (*ManifestResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *ManifestResponse) GetManifest() *Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type Manifest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version          string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	MessageTypes     []*MessageType         `protobuf:"bytes,3,rep,name=message_types,json=messageTypes,proto3" json:"message_types,omitempty"`
	ControlFunctions []*ControlFunctionType `protobuf:"bytes,4,rep,name=control_functions,json=controlFunctions,proto3" json:"control_functions,omitempty"`
	ComponentTypes   []*ComponentType       `protobuf:"bytes,5,rep,name=component_types,json=componentTypes,proto3" json:"component_types,omitempty"`
	TransportTypes   []*TransportType       `protobuf:"bytes,6,rep,name=transport_types,json=transportTypes,proto3" json:"transport_types,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Manifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Manifest) GetMessageTypes() []*MessageType {
	if x != nil {
		return x.MessageTypes
	}
	return nil
}

func (x *Manifest) GetControlFunctions() []*ControlFunctionType {
	if x != nil {
		return x.ControlFunctions
	}
	return nil
}

func (x *Manifest) GetComponentTypes() []*ComponentType {
	if x != nil {
		return x.ComponentTypes
	}
	return nil
}

func (x *Manifest) GetTransportTypes() []*TransportType {
	if x != nil {
		return x.TransportTypes
	}
	return nil
}

type MessageType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Fields        []*FieldSpec           `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageType) Reset() {
	*x = MessageType{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageType) ProtoMessage() {}

func (x *MessageType) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageType.ProtoReflect.Descriptor instead.
func (*MessageType) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *MessageType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageType) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *MessageType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MessageType) GetFields() []*FieldSpec {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ControlFunctionType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Fields        []*FieldSpec           `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlFunctionType) Reset() {
	*x = ControlFunctionType{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlFunctionType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlFunctionType) ProtoMessage() {}

func (x *ControlFunctionType) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlFunctionType.ProtoReflect.Descriptor instead.
func (*ControlFunctionType) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ControlFunctionType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ControlFunctionType) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ControlFunctionType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ControlFunctionType) GetFields() []*FieldSpec {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ComponentType struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Id                        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName               string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Internal                  bool                   `protobuf:"varint,3,opt,name=internal,proto3" json:"internal,omitempty"`
	Description               string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	SupportsMultipleInstances bool                   `protobuf:"varint,5,opt,name=supports_multiple_instances,json=supportsMultipleInstances,proto3" json:"supports_multiple_instances,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ComponentType) Reset() {
	*x = ComponentType{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentType) ProtoMessage() {}

func (x *ComponentType) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentType.ProtoReflect.Descriptor instead.
func (*ComponentType) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ComponentType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ComponentType) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ComponentType) GetInternal() bool {
	if x != nil {
		return x.Internal
	}
	return false
}

func (x *ComponentType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ComponentType) GetSupportsMultipleInstances() bool {
	if x != nil {
		return x.SupportsMultipleInstances
	}
	return false
}

type TransportType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Internal      bool                   `protobuf:"varint,4,opt,name=internal,proto3" json:"internal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransportType) Reset() {
	*x = TransportType{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportType) ProtoMessage() {}

func (x *TransportType) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportType.ProtoReflect.Descriptor instead.
func (*TransportType) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *TransportType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransportType) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *TransportType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TransportType) GetInternal() bool {
	if x != nil {
		return x.Internal
	}
	return false
}

type FieldSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          FieldType              `protobuf:"varint,2,opt,name=type,proto3,enum=simsdkrpc.FieldType" json:"type,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	EnumValues    []string               `protobuf:"bytes,4,rep,name=enum_values,json=enumValues,proto3" json:"enum_values,omitempty"`
	Repeated      bool                   `protobuf:"varint,5,opt,name=repeated,proto3" json:"repeated,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Subtype       FieldType              `protobuf:"varint,7,opt,name=subtype,proto3,enum=simsdkrpc.FieldType" json:"subtype,omitempty"`
	ObjectFields  []*FieldSpec           `protobuf:"bytes,8,rep,name=object_fields,json=objectFields,proto3" json:"object_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldSpec) Reset() {
	*x = FieldSpec{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldSpec) ProtoMessage() {}

func (x *FieldSpec) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldSpec.ProtoReflect.Descriptor instead.
func (*FieldSpec) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *FieldSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldSpec) GetType() FieldType {
	if x != nil {
		return x.Type
	}
	return FieldType_FIELD_TYPE_UNSPECIFIED
}

func (x *FieldSpec) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *FieldSpec) GetEnumValues() []string {
	if x != nil {
		return x.EnumValues
	}
	return nil
}

func (x *FieldSpec) GetRepeated() bool {
	if x != nil {
		return x.Repeated
	}
	return false
}

func (x *FieldSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FieldSpec) GetSubtype() FieldType {
	if x != nil {
		return x.Subtype
	}
	return FieldType_FIELD_TYPE_UNSPECIFIED
}

func (x *FieldSpec) GetObjectFields() []*FieldSpec {
	if x != nil {
		return x.ObjectFields
	}
	return nil
}

type CreateComponentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentType string                 `protobuf:"bytes,1,opt,name=component_type,json=componentType,proto3" json:"component_type,omitempty"`
	ComponentId   string                 `protobuf:"bytes,2,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateComponentRequest) Reset() {
	*x = CreateComponentRequest{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateComponentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateComponentRequest) ProtoMessage() {}

func (x *CreateComponentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateComponentRequest.ProtoReflect.Descriptor instead.
func (*CreateComponentRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *CreateComponentRequest) GetComponentType() string {
	if x != nil {
		return x.ComponentType
	}
	return ""
}

func (x *CreateComponentRequest) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *CreateComponentRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type CreateComponentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateComponentResponse) Reset() {
	*x = CreateComponentResponse{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateComponentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateComponentResponse) ProtoMessage() {}

func (x *CreateComponentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateComponentResponse.ProtoReflect.Descriptor instead.
func (*CreateComponentResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

type SimMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageType   string                 `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ComponentId   string                 `protobuf:"bytes,3,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimMessage) Reset() {
	*x = SimMessage{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimMessage) ProtoMessage() {}

func (x *SimMessage) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimMessage.ProtoReflect.Descriptor instead.
func (*SimMessage) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *SimMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *SimMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SimMessage) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *SimMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SimMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MessageResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OutboundMessages []*SimMessage          `protobuf:"bytes,1,rep,name=outbound_messages,json=outboundMessages,proto3" json:"outbound_messages,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *MessageResponse) GetOutboundMessages() []*SimMessage {
	if x != nil {
		return x.OutboundMessages
	}
	return nil
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\tsimsdkrpc\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x11\n" +
	"\x0fManifestRequest\"C\n" +
	"\x10ManifestResponse\x12/\n" +
	"\bmanifest\x18\x01 \x01(\v2\x13.simsdkrpc.ManifestR\bmanifest\"\xc8\x02\n" +
	"\bManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12;\n" +
	"\rmessage_types\x18\x03 \x03(\v2\x16.simsdkrpc.MessageTypeR\fmessageTypes\x12K\n" +
	"\x11control_functions\x18\x04 \x03(\v2\x1e.simsdkrpc.ControlFunctionTypeR\x10controlFunctions\x12A\n" +
	"\x0fcomponent_types\x18\x05 \x03(\v2\x18.simsdkrpc.ComponentTypeR\x0ecomponentTypes\x12A\n" +
	"\x0ftransport_types\x18\x06 \x03(\v2\x18.simsdkrpc.TransportTypeR\x0etransportTypes\"\x90\x01\n" +
	"\vMessageType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12,\n" +
	"\x06fields\x18\x04 \x03(\v2\x14.simsdkrpc.FieldSpecR\x06fields\"\x98\x01\n" +
	"\x13ControlFunctionType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12,\n" +
	"\x06fields\x18\x04 \x03(\v2\x14.simsdkrpc.FieldSpecR\x06fields\"\xc0\x01\n" +
	"\rComponentType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1a\n" +
	"\binternal\x18\x03 \x01(\bR\binternal\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12>\n" +
	"\x1bsupports_multiple_instances\x18\x05 \x01(\bR\x19supportsMultipleInstances\"\x80\x01\n" +
	"\rTransportType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\binternal\x18\x04 \x01(\bR\binternal\"\xaf\x02\n" +
	"\tFieldSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.simsdkrpc.FieldTypeR\x04type\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12\x1f\n" +
	"\venum_values\x18\x04 \x03(\tR\n" +
	"enumValues\x12\x1a\n" +
	"\brepeated\x18\x05 \x01(\bR\brepeated\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12.\n" +
	"\asubtype\x18\a \x01(\x0e2\x14.simsdkrpc.FieldTypeR\asubtype\x129\n" +
	"\robject_fields\x18\b \x03(\v2\x14.simsdkrpc.FieldSpecR\fobjectFields\"\xf4\x01\n" +
	"\x16CreateComponentRequest\x12%\n" +
	"\x0ecomponent_type\x18\x01 \x01(\tR\rcomponentType\x12!\n" +
	"\fcomponent_id\x18\x02 \x01(\tR\vcomponentId\x12Q\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v21.simsdkrpc.CreateComponentRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x19\n" +
	"\x17CreateComponentResponse\"\x89\x02\n" +
	"\n" +
	"SimMessage\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12!\n" +
	"\fcomponent_id\x18\x03 \x01(\tR\vcomponentId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12?\n" +
	"\bmetadata\x18\x05 \x03(\v2#.simsdkrpc.SimMessage.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\x0fMessageResponse\x12B\n" +
	"\x11outbound_messages\x18\x01 \x03(\v2\x15.simsdkrpc.SimMessageR\x10outboundMessages*\x8e\x01\n" +
	"\tFieldType\x12\x1a\n" +
	"\x16FIELD_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06STRING\x10\x01\x12\a\n" +
	"\x03INT\x10\x02\x12\b\n" +
	"\x04UINT\x10\x03\x12\t\n" +
	"\x05FLOAT\x10\x04\x12\b\n" +
	"\x04BOOL\x10\x05\x12\b\n" +
	"\x04ENUM\x10\x06\x12\r\n" +
	"\tTIMESTAMP\x10\a\x12\f\n" +
	"\bREPEATED\x10\b\x12\n" +
	"\n" +
	"\x06OBJECT\x10\t2\xcf\x02\n" +
	"\rPluginService\x12F\n" +
	"\vGetManifest\x12\x1a.simsdkrpc.ManifestRequest\x1a\x1b.simsdkrpc.ManifestResponse\x12`\n" +
	"\x17CreateComponentInstance\x12!.simsdkrpc.CreateComponentRequest\x1a\".simsdkrpc.CreateComponentResponse\x12P\n" +
	"\x18DestroyComponentInstance\x12\x1c.google.protobuf.StringValue\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\rHandleMessage\x12\x15.simsdkrpc.SimMessage\x1a\x1a.simsdkrpc.MessageResponseB6Z4github.com/neurosimio/simsdk/rpc/simsdkrpc;simsdkrpcb\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_plugin_proto_goTypes = []any{
	(FieldType)(0),                  // 0: simsdkrpc.FieldType
	(*ManifestRequest)(nil),         // 1: simsdkrpc.ManifestRequest
	(*ManifestResponse)(nil),        // 2: simsdkrpc.ManifestResponse
	(*Manifest)(nil),                // 3: simsdkrpc.Manifest
	(*MessageType)(nil),             // 4: simsdkrpc.MessageType
	(*ControlFunctionType)(nil),     // 5: simsdkrpc.ControlFunctionType
	(*ComponentType)(nil),           // 6: simsdkrpc.ComponentType
	(*TransportType)(nil),           // 7: simsdkrpc.TransportType
	(*FieldSpec)(nil),               // 8: simsdkrpc.FieldSpec
	(*CreateComponentRequest)(nil),  // 9: simsdkrpc.CreateComponentRequest
	(*CreateComponentResponse)(nil), // 10: simsdkrpc.CreateComponentResponse
	(*SimMessage)(nil),              // 11: simsdkrpc.SimMessage
	(*MessageResponse)(nil),         // 12: simsdkrpc.MessageResponse
	nil,                             // 13: simsdkrpc.CreateComponentRequest.ParametersEntry
	nil,                             // 14: simsdkrpc.SimMessage.MetadataEntry
	(*wrapperspb.StringValue)(nil),  // 15: google.protobuf.StringValue
	(*emptypb.Empty)(nil),           // 16: google.protobuf.Empty
}
var file_plugin_proto_depIdxs = []int32{
	3,  // 0: simsdkrpc.ManifestResponse.manifest:type_name -> simsdkrpc.Manifest
	4,  // 1: simsdkrpc.Manifest.message_types:type_name -> simsdkrpc.MessageType
	5,  // 2: simsdkrpc.Manifest.control_functions:type_name -> simsdkrpc.ControlFunctionType
	6,  // 3: simsdkrpc.Manifest.component_types:type_name -> simsdkrpc.ComponentType
	7,  // 4: simsdkrpc.Manifest.transport_types:type_name -> simsdkrpc.TransportType
	8,  // 5: simsdkrpc.MessageType.fields:type_name -> simsdkrpc.FieldSpec
	8,  // 6: simsdkrpc.ControlFunctionType.fields:type_name -> simsdkrpc.FieldSpec
	0,  // 7: simsdkrpc.FieldSpec.type:type_name -> simsdkrpc.FieldType
	0,  // 8: simsdkrpc.FieldSpec.subtype:type_name -> simsdkrpc.FieldType
	8,  // 9: simsdkrpc.FieldSpec.object_fields:type_name -> simsdkrpc.FieldSpec
	13, // 10: simsdkrpc.CreateComponentRequest.parameters:type_name -> simsdkrpc.CreateComponentRequest.ParametersEntry
	14, // 11: simsdkrpc.SimMessage.metadata:type_name -> simsdkrpc.SimMessage.MetadataEntry
	11, // 12: simsdkrpc.MessageResponse.outbound_messages:type_name -> simsdkrpc.SimMessage
	1,  // 13: simsdkrpc.PluginService.GetManifest:input_type -> simsdkrpc.ManifestRequest
	9,  // 14: simsdkrpc.PluginService.CreateComponentInstance:input_type -> simsdkrpc.CreateComponentRequest
	15, // 15: simsdkrpc.PluginService.DestroyComponentInstance:input_type -> google.protobuf.StringValue
	11, // 16: simsdkrpc.PluginService.HandleMessage:input_type -> simsdkrpc.SimMessage
	2,  // 17: simsdkrpc.PluginService.GetManifest:output_type -> simsdkrpc.ManifestResponse
	10, // 18: simsdkrpc.PluginService.CreateComponentInstance:output_type -> simsdkrpc.CreateComponentResponse
	16, // 19: simsdkrpc.PluginService.DestroyComponentInstance:output_type -> google.protobuf.Empty
	12, // 20: simsdkrpc.PluginService.HandleMessage:output_type -> simsdkrpc.MessageResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
